project:
  type: website
  output-dir: docs

styles:
    - styles.css
    
website:
  navbar:
    search: false
    background-color: "#000000"
    right:
      - text: "Home"
        file: index.html
      - text: "Blog"
        file: blog.qmd
      - text: "Projects"
        file: project.qmd
      - text: "Work"
        file: work.html
      - text: "CV"
        file: cv.pdf

format:
  html:
    theme: cosmo
    css: styles.css





