<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Neil Dcruze">
<meta name="dcterms.date" content="2023-03-28">
<meta name="description" content="Training a Model to predict Employment for Different Individuals and then Audit the Model to Display Potential Biases across different Racial Groups">

<title>Auditing Allocative Bias</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html">Blog</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../project.html">Projects</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../work.html">Work</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.pdf">CV</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Auditing Allocative Bias</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
  </div>
  </div>

<div>
  <div class="description">
    Training a Model to predict Employment for Different Individuals and then Audit the Model to Display Potential Biases across different Racial Groups
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Neil Dcruze </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 28, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
In machine learning, <i>bias</i> refers to the production of consistently prejudiced outcomes by the algorithm, which can create unfair circumstances on multiple fronts. In this blog post, we aim to explore that <i>bias</i> by:
<ol>
<li>
Creating a machine learning model that predicts an individual characteristic like: employment status or income, on the basis of other demographic characteristics
</li><li>
Performing a “fairness audit” in order to assess whether our algorithm displays bias with respect to demographic characteristics (race or sex)
</li></ol>
<p>For the purpose of this blog post, we will be using the <u>folktables</u> package to download data on which we will perform the <i>bias audit</i>. Here, we will be using the data of individuals from the state of New York!</p>
</section>
<section id="loading-and-setting-up-the-data" class="level1">
<h1>Loading and Setting Up the Data</h1>
<p>First, let us load the data and prepare it for our purposes:</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> folktables <span class="im">import</span> ACSDataSource, ACSEmployment, BasicProblem, adult_filter</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> PolynomialFeatures</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.pipeline <span class="im">import</span> Pipeline</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> confusion_matrix</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>STATE <span class="op">=</span> <span class="st">'NY'</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>data_source <span class="op">=</span> ACSDataSource(survey_year<span class="op">=</span><span class="st">'2018'</span>, horizon<span class="op">=</span><span class="st">'1-Year'</span>, survey<span class="op">=</span><span class="st">'person'</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>acs_data <span class="op">=</span> data_source.get_data(states<span class="op">=</span>[STATE], download <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Downloading data for 2018 1-Year person survey for NY...</code></pre>
</div>
</div>
<p>Now, let us examine the first few rows of the data, to get an idea of it:</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>acs_data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>RT</th>
      <th>SERIALNO</th>
      <th>DIVISION</th>
      <th>SPORDER</th>
      <th>PUMA</th>
      <th>REGION</th>
      <th>ST</th>
      <th>ADJINC</th>
      <th>PWGTP</th>
      <th>AGEP</th>
      <th>...</th>
      <th>PWGTP71</th>
      <th>PWGTP72</th>
      <th>PWGTP73</th>
      <th>PWGTP74</th>
      <th>PWGTP75</th>
      <th>PWGTP76</th>
      <th>PWGTP77</th>
      <th>PWGTP78</th>
      <th>PWGTP79</th>
      <th>PWGTP80</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>P</td>
      <td>2018GQ0000012</td>
      <td>2</td>
      <td>1</td>
      <td>3802</td>
      <td>1</td>
      <td>36</td>
      <td>1013097</td>
      <td>145</td>
      <td>26</td>
      <td>...</td>
      <td>146</td>
      <td>146</td>
      <td>21</td>
      <td>24</td>
      <td>266</td>
      <td>263</td>
      <td>21</td>
      <td>146</td>
      <td>265</td>
      <td>144</td>
    </tr>
    <tr>
      <th>1</th>
      <td>P</td>
      <td>2018GQ0000040</td>
      <td>2</td>
      <td>1</td>
      <td>2702</td>
      <td>1</td>
      <td>36</td>
      <td>1013097</td>
      <td>43</td>
      <td>21</td>
      <td>...</td>
      <td>6</td>
      <td>42</td>
      <td>43</td>
      <td>7</td>
      <td>40</td>
      <td>6</td>
      <td>43</td>
      <td>40</td>
      <td>42</td>
      <td>6</td>
    </tr>
    <tr>
      <th>2</th>
      <td>P</td>
      <td>2018GQ0000060</td>
      <td>2</td>
      <td>1</td>
      <td>2001</td>
      <td>1</td>
      <td>36</td>
      <td>1013097</td>
      <td>88</td>
      <td>18</td>
      <td>...</td>
      <td>88</td>
      <td>163</td>
      <td>161</td>
      <td>162</td>
      <td>87</td>
      <td>12</td>
      <td>162</td>
      <td>88</td>
      <td>87</td>
      <td>88</td>
    </tr>
    <tr>
      <th>3</th>
      <td>P</td>
      <td>2018GQ0000081</td>
      <td>2</td>
      <td>1</td>
      <td>2401</td>
      <td>1</td>
      <td>36</td>
      <td>1013097</td>
      <td>109</td>
      <td>85</td>
      <td>...</td>
      <td>17</td>
      <td>15</td>
      <td>111</td>
      <td>107</td>
      <td>17</td>
      <td>196</td>
      <td>109</td>
      <td>200</td>
      <td>198</td>
      <td>111</td>
    </tr>
    <tr>
      <th>4</th>
      <td>P</td>
      <td>2018GQ0000103</td>
      <td>2</td>
      <td>1</td>
      <td>1400</td>
      <td>1</td>
      <td>36</td>
      <td>1013097</td>
      <td>83</td>
      <td>19</td>
      <td>...</td>
      <td>81</td>
      <td>12</td>
      <td>80</td>
      <td>154</td>
      <td>12</td>
      <td>80</td>
      <td>12</td>
      <td>83</td>
      <td>152</td>
      <td>154</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 286 columns</p>
</div>
</div>
</div>
<p>Each row in the above dataset corresponds to an individual citizen of New York who filled out the PUMS survey of 2018. Therefore, what we have is a <span class="math inline">\(n\)</span>x<span class="math inline">\(p\)</span> matrix, where <span class="math inline">\(n\)</span> = number of data points, and <span class="math inline">\(p\)</span> = number of features. We can see that there are a bunch of features in this dataset, and all of them might not be pertinent for our analysis. Therefore, we are only going to choose the features which are relevant for this blog post:</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>possible_features<span class="op">=</span>[<span class="st">'AGEP'</span>, <span class="st">'SCHL'</span>, <span class="st">'MAR'</span>, <span class="st">'RELP'</span>, <span class="st">'DIS'</span>, <span class="st">'ESP'</span>, <span class="st">'CIT'</span>, <span class="st">'MIG'</span>, <span class="st">'MIL'</span>, <span class="st">'ANC'</span>, <span class="st">'NATIVITY'</span>, <span class="st">'DEAR'</span>, <span class="st">'DEYE'</span>, <span class="st">'DREM'</span>, <span class="st">'SEX'</span>, <span class="st">'RAC1P'</span>, <span class="st">'ESR'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, since we want to predict <i>ESR</i> - Employment Status, based on every relevant feature except the <i>RAC1P</i> - Race, we want to remove these two features from the list of <i>possible_features</i>. This is because one of these features is our target (output), and the we are excluding the other one (race) to study racial bias in our machine learning model:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>features_to_use <span class="op">=</span> [f <span class="cf">for</span> f <span class="kw">in</span> possible_features <span class="cf">if</span> f <span class="kw">not</span> <span class="kw">in</span> [<span class="st">"ESR"</span>, <span class="st">"RAC1P"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
Now that we know:
<ol>
<li>
Features (features_to_use): the features we wish to use for the prediction
</li><li>
Target (ESR): the thing we are trying to predict
</li><li>
Group (RAC1P): the group by which we wish to audit the bias
</li></ol>
<p>We can go ahead and create a <i>BasicProblem</i>:</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>EmploymentProblem <span class="op">=</span> BasicProblem(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    features<span class="op">=</span>features_to_use,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    target<span class="op">=</span><span class="st">'ESR'</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    target_transform<span class="op">=</span><span class="kw">lambda</span> x: x <span class="op">==</span> <span class="dv">1</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    group<span class="op">=</span><span class="st">'RAC1P'</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    preprocess<span class="op">=</span><span class="kw">lambda</span> x: x,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    postprocess<span class="op">=</span><span class="kw">lambda</span> x: np.nan_to_num(x, <span class="op">-</span><span class="dv">1</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can go ahead and extract our feature matrix, output labels vector, and the group (race) vector as numpy objects:</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>features, label, group <span class="op">=</span> EmploymentProblem.df_to_numpy(acs_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, that we have all the necessary data, we can split our data into <i>training data</i> and <i>testing data</i>. Here, 80% of the data will be used for training and the remaining 20% will be used for testing:</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test, group_train, group_test <span class="op">=</span> train_test_split(features, label, group, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="basic-descriptives" class="level1">
<h1>Basic Descriptives</h1>
<p>Now, that we have our data set up, we can address some basic descriptives of the data which will aid us in our analysis later on. For this it is useful to make a <i>data frame</i> out of our data:</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame(X_train, columns <span class="op">=</span> features_to_use)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"group"</span>] <span class="op">=</span> group_train</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"label"</span>] <span class="op">=</span> y_train</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Question 1: How many individuals are in the data?</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Answer 1: There are </span><span class="sc">{</span>df<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> people in the training data set!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Answer 1: There are 157573 people in the training data set!</code></pre>
</div>
</div>
<p>Question 2: Of these individuals, what proportion have target label equal to 1? In employment prediction, these would correspond to employed individuals.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>employed <span class="op">=</span> df[df[<span class="st">'label'</span>]<span class="op">==</span><span class="va">True</span>]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Answer 2: There are </span><span class="sc">{</span>employed<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> number of people in the training data set who are employed - have target label equal to True!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Answer 2: There are 73262 number of people in the training data set who are employed - have target label equal to True!</code></pre>
</div>
</div>
<p>Question 3: Of these individuals, how many are in each of the groups? <br><br>Answer 3: We can see a breakdown of how many people of each racial group are employed:</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(employed.groupby(<span class="st">'group'</span>).size())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>group
1    52646
2     8030
3      177
4        3
5       66
6     6778
7       23
8     3860
9     1679
dtype: int64</code></pre>
</div>
</div>
<p>Question 4: In each group, what proportion of individuals have target label equal to 1? <br><br>Answer 4: The proportion of individuals in each group who are employed (have target label 1):</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.groupby([<span class="st">'group'</span>])[[<span class="st">'label'</span>]].aggregate([np.mean]).<span class="bu">round</span>(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      label
       mean
group      
1      0.47
2      0.42
3      0.43
4      0.75
5      0.34
6      0.50
7      0.42
8      0.44
9      0.37</code></pre>
</div>
</div>
<p>Question 5: Check for intersectional trends by studying the proportion of positive target labels broken out by your chosen group labels and an additional group label. For example, if you chose race (RAC1P) as your group, then you could also choose sex (SEX) and compute the proportion of positive labels by both race and sex. <br><br> Answer 5: For answering this question, first let us look at the positive labels broken down only by SEX. Then we can look at the intersectionality of RACE and SEX, by looking at positive labels broken down by these two group labels.</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.groupby([<span class="st">'SEX'</span>])[[<span class="st">'label'</span>]].aggregate([np.mean]).<span class="bu">round</span>(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    label
     mean
SEX      
1.0  0.49
2.0  0.44</code></pre>
</div>
</div>
<p>We can see that: 49% of MEN (1.0) are employed, while 44% of WOMEN (2.0) are employed! Now let us look at the positive target labels broken down by both RACE and SEX:</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.groupby([<span class="st">'group'</span>,<span class="st">'SEX'</span>])[[<span class="st">'label'</span>]].aggregate([np.mean]).<span class="bu">round</span>(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          label
           mean
group SEX      
1     1.0  0.50
      2.0  0.45
2     1.0  0.40
      2.0  0.44
3     1.0  0.46
      2.0  0.39
4     1.0  1.00
      2.0  0.50
5     1.0  0.39
      2.0  0.29
6     1.0  0.54
      2.0  0.46
7     1.0  0.35
      2.0  0.50
8     1.0  0.48
      2.0  0.41
9     1.0  0.36
      2.0  0.38</code></pre>
</div>
</div>
<p>We can visualize this data using a bar chart for easier understanding:</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>bplot <span class="op">=</span> sns.barplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">"group"</span>, y<span class="op">=</span><span class="st">"label"</span>, hue<span class="op">=</span><span class="st">"SEX"</span>, errorbar<span class="op">=</span>(<span class="st">'ci'</span>, <span class="dv">0</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>bplot.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"Different Racial Groups"</span>, ylabel<span class="op">=</span><span class="st">"Proportion of People Employed"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>plt.show(bplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-16-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>Therefore, it is apparent that the proportion of women who are employed, is less than the proportion of men who are employed, in almost all racial groups except racial group 2, 7, and 9. Not only that, some racial groups have a really high disparity between the proportion of men who are employed versus the proportion of women who are employed. For instance, in racial group 4: the proportion of men who are employed is roughly 100%, while the proportion of women who are employed is only 50%.</p>
</section>
<section id="training-the-model" class="level1">
<h1>Training the Model</h1>
Now that we have answered the basic descriptive questions, we are ready to train our model on the training data. For this blog post, the chosen machine learning model is: <i>Logistic Regression</i>, and we will be tuning the polynomial features (number of degrees) in our <i>Logistic Regression</i> model. Therefore, our workflow is going to be:
<ol>
<li>
Creating a function that will utilize <i>Pipeline</i> to make it easier for us to construct a <i>Logistic Regression</i> model with certain number of polynomial features (a certain number of degrees)
</li><li>
Using cross-validation to select the best degree (number of polynomial features)
</li><li>
Creating a Logistic Regression model with the best number of degrees that we found in Step (2) and fitting it on our <i>training data</i>
</li><li>
Checking the performance of our model on the <i>testing data</i>
</li></ol>
<p>Let us get started with creating the function which utilizes Pipeline, for easier construction of our Logistic Regression models:</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> polyLR(deg):</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> Pipeline([(<span class="st">"poly"</span>, PolynomialFeatures(degree <span class="op">=</span> deg)),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                   (<span class="st">"LR"</span>, LogisticRegression(penalty <span class="op">=</span> <span class="va">None</span>, max_iter <span class="op">=</span> <span class="dv">1000</span>))])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we can use cross-validation to select which degree (number of polynomial features) works best for our data. The main principle behind cross-validation is that you can divide your training data into <span class="math inline">\(k\)</span> folds (chunks), and then train your model over <span class="math inline">\(k-1\)</span> chunks and then <i>validate</i> it over the last remaining chunk. Therefore, if you divide your training data into <span class="math inline">\(4\)</span> chunks - let us say - then each one of the <span class="math inline">\(4\)</span> chunks will act as the <i>validation data</i> once, with the rest of the chunks being used as <i>training data</i>. Therefore, in case of <span class="math inline">\(4\)</span> chunks, the <u>fit</u> function will be called <span class="math inline">\(4\)</span> times. Now, we can find the <i>mean</i> cross-validation score for varying degrees (number of polynomial features), and the degree which has the highest cross-validation score is most likely to perform the best on the <i>testing data</i>:</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> deg <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>):</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>    plr <span class="op">=</span> polyLR(deg <span class="op">=</span> deg)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    cv_scores <span class="op">=</span> cross_val_score(plr, X_train, y_train, cv <span class="op">=</span> <span class="dv">5</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    mean_score <span class="op">=</span> cv_scores.mean()</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Polynomial Degree = </span><span class="sc">{</span>deg<span class="sc">}</span><span class="ss">, Score = </span><span class="sc">{</span>mean_score<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Polynomial Degree = 0, Score = 0.535
Polynomial Degree = 1, Score = 0.772
Polynomial Degree = 2, Score = 0.811
Polynomial Degree = 3, Score = 0.809
Polynomial Degree = 4, Score = 0.806</code></pre>
</div>
</div>
<p>Therefore, for our purposes it seems that Polynomial Degree = <span class="math inline">\(2\)</span> yields the best results during our cross-validation, so we can assume that this degree is also likely to perform the best on our <i>testing data</i>. Now, we can go ahead and create a Logistic Regression model with degrees = <span class="math inline">\(2\)</span>:</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>plr <span class="op">=</span> polyLR(deg <span class="op">=</span> <span class="dv">2</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>plr.fit(X_train, y_train)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Score on Training Data: </span><span class="sc">{</span>plr<span class="sc">.</span>score(X_train, y_train)<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Score on Training Data: 0.811</code></pre>
</div>
</div>
<p>Now, finally we can check the performance of our model on the <i>testing data</i>:</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Score on Testing Data: </span><span class="sc">{</span>plr<span class="sc">.</span>score(X_test, y_test)<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Score on Testing Data: 0.811</code></pre>
</div>
</div>
<p>Therefore, we can see that we achieved approximately <span class="math inline">\(81\)</span>% accuracy on our <i>testing data</i>!</p>
</section>
<section id="auditing-the-model" class="level1">
<h1>Auditing the Model</h1>
Now that our model is trained, we can perform an audit on the test data where we can answer questions on our <i>testing data</i>. It is helpful to use a confusion matrix while answering these questions. A confusion matrix, is a matrix containing information about the model’s prediction and the kind of errors it makes:
<ol>
<li>
True Negative: Negative Data + Classified Negative by Model
</li><li>
False Positive: Negative Data + Wrongly Classified Positive by Model
</li><li>
False Negative: Positive Data + Wrongly Classified Negative by Model
</li><li>
True Positive: Positive Data + Classified Positive by Model
</li></ol>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> plr.predict(X_test)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>cm <span class="op">=</span> confusion_matrix(y_test, y_pred)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"The Confusion Matrix:</span><span class="ch">\n</span><span class="ss"> </span><span class="sc">{</span>cm<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>tn, fp, fn, tp <span class="op">=</span> cm[<span class="dv">0</span>][<span class="dv">0</span>], cm[<span class="dv">0</span>][<span class="dv">1</span>], cm[<span class="dv">1</span>][<span class="dv">0</span>], cm[<span class="dv">1</span>][<span class="dv">1</span>]</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">True Negative: </span><span class="sc">{</span>tn<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"False Positive: </span><span class="sc">{</span>fp<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"False Negative: </span><span class="sc">{</span>fn<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"True Positive: </span><span class="sc">{</span>tp<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The Confusion Matrix:
 [[16235  4952]
 [ 2491 15716]]

True Negative: 16235
False Positive: 4952
False Negative: 2491
True Positive: 15716</code></pre>
</div>
</div>
That above is our confusion matrix with the information we talked about above. Now, it is useful to define some concepts and associated formulae:
<ol>
<li>
<u>Overall Accuracy</u>: proportion of correct predictions made over the total number of predictions made <br><br>
<center>
<span class="math inline">\(\text{Overall Accuracy} = \frac{TN + TP}{TN + TP + FP + FN}\)</span>
</center>
<br>
</li><li>
<u>Positive Predictive Value (PPV)</u>: probability that a positive prediction made by the model is actually correct <br><br>
<center>
<span class="math inline">\(\text{PPV} = \frac{TP}{TP + FP}\)</span>
</center>
<br>
</li><li>
<u>False Positive Rate (FPR)</u>: proportion of negative examples that were incorrectly classified as positve<br><br>
<center>
<span class="math inline">\(\text{FPR} = \frac{FP}{FP + TN}\)</span>
</center>
<br>
</li><li>
<u>False Negative Rate (FNR)</u>: proportion of positive examples that were incorrectly classified as negative <br><br>
<center>
<span class="math inline">\(\text{FNR} = \frac{FN}{FN + TP}\)</span>
</center>
</li></ol>
<section id="overall-measures" class="level3">
<h3 class="anchored" data-anchor-id="overall-measures">Overall Measures</h3>
<ol type="1">
<li>What is the overall accuracy of our model?</li>
</ol>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>overallAccuracy <span class="op">=</span> ((tn <span class="op">+</span> tp)<span class="op">/</span>(tn <span class="op">+</span> tp <span class="op">+</span> fp <span class="op">+</span> fn)).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Overall Accuracy of the Model is </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(overallAccuracy<span class="op">*</span><span class="dv">100</span>,<span class="dv">3</span>)<span class="sc">}</span><span class="ss">%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Overall Accuracy of the Model is 81.1%</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>What is the Positive Predictive Value (PPV) of our model?</li>
</ol>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ppv <span class="op">=</span> ((tp)<span class="op">/</span>(tp <span class="op">+</span> fp)).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"PPV of the Model: </span><span class="sc">{</span>ppv<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"This means that </span><span class="sc">{</span>ppv<span class="sc">}</span><span class="ss"> of all positive predictions made by the model are actually correct!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>PPV of the Model: 0.76
This means that 0.76 of all positive predictions made by the model are actually correct!</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>What are the overall False Positive and False Negative Rates (FPR and FNR) for our model?</li>
</ol>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fpr <span class="op">=</span> ((fp)<span class="op">/</span>(fp <span class="op">+</span> tn)).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fnr <span class="op">=</span> ((fn)<span class="op">/</span>(fn <span class="op">+</span> tp)).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"FPR of the Model: </span><span class="sc">{</span>fpr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"This means that </span><span class="sc">{</span>fpr<span class="sc">}</span><span class="ss"> of all negative examples were wrongly classified as positive!"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">FNR of the Model: </span><span class="sc">{</span>fnr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"This means that </span><span class="sc">{</span>fnr<span class="sc">}</span><span class="ss"> of all positive examples were wrongly classified as negative!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>FPR of the Model: 0.234
This means that 0.234 of all negative examples were wrongly classified as positive!

FNR of the Model: 0.137
This means that 0.137 of all positive examples were wrongly classified as negative!</code></pre>
</div>
</div>
</section>
<section id="by-group-measures" class="level3">
<h3 class="anchored" data-anchor-id="by-group-measures">By-Group Measures</h3>
<p>Now, we can go ahead and look at the: Overall Accuracy, PPV, FPR, and FNR for each the 9 subgroups (the different racial groups). We cannot calculate the statistics for <i>Group 4: Alaskan Natives</i> due to lack of sufficient sample:</p>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">1</span>,<span class="dv">4</span>)) <span class="op">+</span> <span class="bu">list</span>(<span class="bu">range</span>(<span class="dv">5</span>, <span class="dv">10</span>)):</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Group </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">:"</span>)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    ix <span class="op">=</span> X_test[group_test <span class="op">==</span> i, :]</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    y_testx <span class="op">=</span> y_test[group_test <span class="op">==</span> i]</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    y_predx <span class="op">=</span> plr.predict(ix)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>    cm <span class="op">=</span> confusion_matrix(y_testx, y_predx)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>    tn, fp, fn, tp <span class="op">=</span> cm[<span class="dv">0</span>][<span class="dv">0</span>], cm[<span class="dv">0</span>][<span class="dv">1</span>], cm[<span class="dv">1</span>][<span class="dv">0</span>], cm[<span class="dv">1</span>][<span class="dv">1</span>]</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>    overallAccuracy <span class="op">=</span> (((tn <span class="op">+</span> tp)<span class="op">/</span>(tn <span class="op">+</span> tp <span class="op">+</span> fp <span class="op">+</span> fn)) <span class="op">*</span> <span class="dv">100</span>).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    ppv <span class="op">=</span> ((tp)<span class="op">/</span>(tp <span class="op">+</span> fp)).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    fpr <span class="op">=</span> ((fp)<span class="op">/</span>(fp <span class="op">+</span> tn)).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    fnr <span class="op">=</span> ((fn)<span class="op">/</span>(fn <span class="op">+</span> tp)).<span class="bu">round</span>(<span class="dv">3</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Overall Accuracy: </span><span class="sc">{</span>overallAccuracy<span class="sc">}</span><span class="ss">%"</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"PPV of the Model: </span><span class="sc">{</span>ppv<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"This means that </span><span class="sc">{</span>ppv<span class="sc">}</span><span class="ss"> of all positive predictions made by the model are actually correct!"</span>)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"FPR of the Model: </span><span class="sc">{</span>fpr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"This means that </span><span class="sc">{</span>fpr<span class="sc">}</span><span class="ss"> of all negative examples were wrongly classified as positive!"</span>)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"FNR of the Model: </span><span class="sc">{</span>fnr<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"This means that </span><span class="sc">{</span>fnr<span class="sc">}</span><span class="ss"> of all positive examples were wrongly classified as negative!"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Group 1:
Overall Accuracy: 81.62%
PPV of the Model: 0.772
This means that 0.772 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.223
This means that 0.223 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.139
This means that 0.139 of all positive examples were wrongly classified as negative!

Group 2:
Overall Accuracy: 80.6%
PPV of the Model: 0.734
This means that 0.734 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.24
This means that 0.24 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.133
This means that 0.133 of all positive examples were wrongly classified as negative!

Group 3:
Overall Accuracy: 73.4%
PPV of the Model: 0.667
This means that 0.667 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.278
This means that 0.278 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.25
This means that 0.25 of all positive examples were wrongly classified as negative!

Group 5:
Overall Accuracy: 78.72%
PPV of the Model: 0.682
This means that 0.682 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.241
This means that 0.241 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.167
This means that 0.167 of all positive examples were wrongly classified as negative!

Group 6:
Overall Accuracy: 78.42%
PPV of the Model: 0.733
This means that 0.733 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.324
This means that 0.324 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.107
This means that 0.107 of all positive examples were wrongly classified as negative!

Group 7:
Overall Accuracy: 70.59%
PPV of the Model: 0.5
This means that 0.5 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.417
This means that 0.417 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.0
This means that 0.0 of all positive examples were wrongly classified as negative!

Group 8:
Overall Accuracy: 77.95%
PPV of the Model: 0.722
This means that 0.722 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.267
This means that 0.267 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.164
This means that 0.164 of all positive examples were wrongly classified as negative!

Group 9:
Overall Accuracy: 85.9%
PPV of the Model: 0.77
This means that 0.77 of all positive predictions made by the model are actually correct!
FPR of the Model: 0.144
This means that 0.144 of all negative examples were wrongly classified as positive!
FNR of the Model: 0.136
This means that 0.136 of all positive examples were wrongly classified as negative!</code></pre>
</div>
</div>
</section>
<section id="bias-measures" class="level3">
<h3 class="anchored" data-anchor-id="bias-measures">Bias Measures</h3>
<section id="is-the-model-approximately-calibrated" class="level5">
<h5 class="anchored" data-anchor-id="is-the-model-approximately-calibrated"><font color="green">Is the model approximately <i>calibrated</i>?</font></h5>
<p>The results clearly show that the <i>PPV</i> varies across the different racial groups. Therefore, our model is not calibrated. For example, if we compared Group 1 (White only): PPV = <span class="math inline">\(0.772\)</span> and Group 2 (Black only): PPV = <span class="math inline">\(0.734\)</span>. Therefore, <span class="math inline">\(\text{PPV}_\text{White} &gt; \text{PPV}_\text{Black}\)</span>, which means that the probability that a positive prediction made by the model is correct, is higher for white people, compared to black people.</p>
</section>
<section id="does-the-model-satisfy-approximate-error-rate-balance" class="level5">
<h5 class="anchored" data-anchor-id="does-the-model-satisfy-approximate-error-rate-balance"><font color="green">Does the model satisfy approximate <i>error rate balance</i>?</font></h5>
<p>The model does not satisfy approximate <i>error rate balance</i>. This is because the <i>FPR</i> and <i>FNR</i> is different across different racial groups. For example, analyzing Group 1 (White only) and Group 2 (Black only): <span class="math inline">\((\text{FPR}_\text{White} = 0.223) &lt; (\text{FPR}_\text{Black}= 0.24)\)</span>, and <span class="math inline">\((\text{FNR}_\text{White} = 0.139) &gt; (\text{FNR}_\text{Black}= 0.133)\)</span>. Therefore, for FPR: the model is more likely to wrongly classify negative examples (not employed) as positive (employed) for Black people compared to White people. For FNR: the model is more likely to wrongly classify positive examples (employed) as negative (not employed) for White people compared to Black people. Therefore, the model makes different types of mistakes more often, across different racial groups.</p>
</section>
<section id="does-the-model-satisfy-statistical-parity" class="level5">
<h5 class="anchored" data-anchor-id="does-the-model-satisfy-statistical-parity"><font color="green">Does the model satisfy <i>statistical parity</i>?</font></h5>
<p>Since, our model has different values of <i>PPV</i> for different racial groups - our model does not satisfy <i>statistical parity</i>!</p>
</section>
</section>
</section>
<section id="concluding-discussions" class="level1">
<h1>Concluding Discussions</h1>
<section id="what-groups-of-people-could-stand-to-benefit-from-a-system-hat-kinds-of-companies-might-want-to-buy-your-model-for-commercial-use" class="level5">
<h5 class="anchored" data-anchor-id="what-groups-of-people-could-stand-to-benefit-from-a-system-hat-kinds-of-companies-might-want-to-buy-your-model-for-commercial-use"><font color="green">What groups of people could stand to benefit from a system? hat kinds of companies might want to buy your model for commercial use?</font></h5>
<p>Since this model predicts whether a person is employed or not, based on other demographic factors. This model could be used to automate or cross-check the process of providing unemployment benefits to individuals. Since this model is more likely to classify unemployed Black people as employed, and more likely to classify employed White people as unemployed, if there were a model which gave people unemployment benefits based on the results of this model - White people would benefit!</p>
</section>
<section id="what-could-be-the-impact-of-deploying-your-model-for-large-scale-prediction-in-commercial-or-governmental-settings-do-you-feel-that-your-model-displays-problematic-bias" class="level5">
<h5 class="anchored" data-anchor-id="what-could-be-the-impact-of-deploying-your-model-for-large-scale-prediction-in-commercial-or-governmental-settings-do-you-feel-that-your-model-displays-problematic-bias"><font color="green">What could be the impact of deploying your model for large-scale prediction in commercial or governmental settings? Do you feel that your model displays problematic bias?</font></h5>
Deploying a model like this for large-scale prediction in commercial or governmental settings will be problematic. This is because, as discussed above: the model will make different kinds of mistakes for different racial groups. Therefore, certain racial groups will benefit more than others - for instance, if the model is used to decide who gets unemployment benefits. Furthermore, this model displays problematic bias. As discussed in the <i>Bias Measures</i> the model is not (does not satisfy):
<ol>
<li>
Calibrated: probability that a positive prediction made by model is correct is different across racial groups
</li><li>
Approximate Error Rate Balance: will make different kinds of mistakes for different racial groups
</li><li>
Statistical Parity: model does not satisfy Statistical Parity (different <i>PPV</i>) for different racial groups
</li></ol>
</section>
<section id="are-there-other-potential-problems-associated-with-deploying-your-model-that-make-you-uncomfortable-how-would-you-propose-addressing-some-of-these-problems" class="level5">
<h5 class="anchored" data-anchor-id="are-there-other-potential-problems-associated-with-deploying-your-model-that-make-you-uncomfortable-how-would-you-propose-addressing-some-of-these-problems"><font color="green">Are there other potential problems associated with deploying your model that make you uncomfortable? How would you propose addressing some of these problems?</font></h5>
<p>If this model were to be used for government purposes: deciding unemployment benefits (mentioned above), I would not feel very comfortable. This is because the model first of all has its own problems and biases, and furthermore automating a process which affects an individual (and humans) so much is very inhumane, as the errors of the model can deeply affect people. If the model did not exhibit the problematic biases discussed above, then maybe the model would be slightly better for deployment. However, it would still not be ideal according to me.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>