project:
  type: website
  output-dir: docs

styles:
    - styles.css
    
website:
  title: "Tushar Mitra"
  #output-dir: docs
  navbar:
    #background: "#112a39"
    right:
      - about.qmd
      - text: "Blog"
        file: index.qmd
      - icon: github
        href: https://github.com/realmitratushar
      - icon: twitter
        href: https://x.com/mitratushar04
      - icon: linkedin
        href: https://www.linkedin.com/in/tushar-mitra-867028261/
      - icon: huggingface
        href: https://huggingface.co/realmitratushar
      - icon: leetcode
        href: https://leetcode.com/u/mitratushar04/

format:
  html:
    title-block-banner: img/starry_night.jpg
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





